# Generated by Django 3.2.8 on 2023-09-09 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitems',
            name='Category',
        ),
        migrations.AddField(
            model_name='menuitems',
            name='category',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.PROTECT, to='LittleLemonApp.category'),
        ),
        migrations.AlterField(
            model_name='menuitems',
            name='featured',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
